comment:
  layout: "reach, diff, flags, files, footer"
  behavior: default
  require_changes: no

coverage:
  status:
    patch:
      default:
        target: 75%
        only_pulls: true
    project:
      default: off
      main:
        target: 75%
        flags: main

flags:
  main:
    paths:
      - Sources/

ignore:
  - "Example/"
  - "Tests/"
  - "TestHosts/"
  - "images/"
  - ".github/"
