language: objective-c
osx_image: xcode10
addons:
  homebrew:
    update: true
    brewfile: true
env:
  - PATH=$HOME/Library/Python/2.7/bin:$PATH
cache:
- bundler: true
install:
- bundle install
- bundle exec danger
- pip install --user -r requirements.txt
script:
- rake test
after_success:
- bash <(curl -s https://codecov.io/bash) -J 'Conduit' -F main
notifications:
  slack:
    secure: d69ZM26mFq7ogFqQImMGk3Yq4ZmuWDgEXOqoKsejP3f7+2XqEjxIpm38pMgXnUx0vt0I2cRfJr3dLMr/nCHftbKAPd8dTqXvmHWi7lmwsWqJqiml3m1VpPG7Rq/bpgT9TweCc3DS3Jiz2eEWW7r6x49rUPKHppEdgmj3A5rWO4fTRBAiUU+PkIeaWOsh7IJJoqBP1l3kqxNhdUfVDJ96TWpPp/Au3inh53QWUV8Ygir/6ACo2uusP+0lBY7dNVRatq9Z6tkfnkc8kIyAI+nPBz1+t2+aSi9T7ajxOsczj9kvxorl2IlCyQdLuGu+wqi2hWtB7uyPFGIlYusfe5WgWbDT6ztJXKoQEXclQkYowDJQdpBTHDh/v16RZE6EY7HLNwehhKiJcpAPW9uHd7WqyBmXzgaKLs/XoBGDbRJ272ahne+qk3ThNhZ0ueSPWzPYGzD6PylkYrD4xd1ms+CzcLFwzMr+KCYJLg7HUJKhoJiBU9U2xw3iU0P4ailw92hIeCWpGjIQmOYbI3bsLCMZzXY3YSB0WlkT/+b4px/zP2qCzarBT5sJDDrBYc6Yrllbc8CLOc4hqA9d3BaskF07x5zWa1N16YFhDYHPZNeivMH00DTDPCPZhUnwz0LZJq/0E5y3RuacMazs3ruqz1VGRihRzs75W3Lt9XfGo1Jq7os=
