#!/usr/bin/env bash
DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

which gunicorn >/dev/null 2>&1 || { echo -e >&2 'gunicorn must be installed in order to spin up a local httpbin webserver:\n$ pip install gunicorn'; exit 1; }
which npm > /dev/null 2>&1 || { echo -e >&2 'npm must be installed in order to spin up a local OAuth2 server:\n$ brew install npm'; exit 1; }

# Make sure httpbin and gevent are installed
$(pip freeze | grep httpbin >/dev/null 2>&1) && $(pip freeze | grep gevent >/dev/null 2>&1) || { echo -e >&2 'httpbin and gevent must be installed for the needed app environment:\n$ pip install httbin\n$pip install gevent'; exit 1; }

# Starts a local webserver daemon using the installed httpbin app (default config) with 4 async workers
gunicorn httpbin:app -b localhost:3333 -w 4 -D -k gevent || { echo -e >&2 'Failed to start webserver daemon'; exit 1; }

# Starts a separate local, in-memory OAuth2 Node.js webserver
active_pid=$(
	cd $DIR/oauth-test-server/
	npm install > /dev/null 2>&1
	nohup npm start 2>/dev/null 1>/dev/null&
	echo $!
)

# Adds the resulting process ID to a simple line-separated list to later be killed
echo $active_pid >> $DIR/.active_pids