name: CI

on:
  push:
    branches: [ master, main, release/* ]
  pull_request:
    branches: [ master, main, release/* ]

jobs:
  build:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build and Test
      run: swift test
