name: Swift

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
    - name: Install bundle
      run: bundle install
    - name: Run Danger
      run: bundle exec danger
    - name: Install local web server
      run: pip install --user -r requirements.txt
    - name: Run tests
      run: rake test
